services:
  readme-notification-mongo:
    image: mongo:4.4
    restart: always
    container_name: readme-notification-mongo

    command: mongod --port ${MONGO_PORT}

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:${MONGO_PORT}/?authSource=${MONGO_DB}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    volumes:
      - readme-notification-mongo:/data/db

  readme-notification-mongo-ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: readme-notification-mongo-ui
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@readme-notification-mongo:${MONGO_PORT}/
      PORT: ${MONGO_EXPRESS_PORT}

  readme-notification-rabbit:
    image: rabbitmq:3-management
    restart: always
    container_name: readme-notification-rabbit
    ports:
      - ${RABBIT_PORT}:${RABBIT_PORT}
      - ${RABBIT_MANAGEMENT_PORT}:${RABBIT_MANAGEMENT_PORT}

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
      RABBITMQ_NODE_PORT: ${RABBIT_PORT}

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  readme-notification-fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: 'readme-notification-fakesmtp'
    hostname: 'readme-notification-fakesmtp'
    ports:
      - '${FAKE_SMTP_PORT}:${FAKE_SMTP_PORT}'
      - '${FAKE_SMTP_UI_PORT}:${FAKE_SMTP_UI_PORT}'

    environment:
      SPRING_APPLICATION_JSON: '{"server.port":${FAKE_SMTP_UI_PORT}}'

volumes:
  readme-notification-mongo:
